// Shared sitemap data - single source of truth
export const sitemapPages = [
  {
    url: '',
    href: '/',
    title: 'Home',
    priority: '1.0',
    changefreq: 'weekly',
    description:
      'Pradumna Saraf - Developer Advocate, Docker Captain, and Open Source evangelist',
    category: 'Main',
    priorityLabel: 'High',
  },
  {
    url: '/timeline',
    href: '/timeline',
    title: 'Timeline',
    priority: '0.9',
    changefreq: 'monthly',
    description: 'Career timeline and major milestones',
    category: 'Professional',
    priorityLabel: 'High',
  },
  {
    url: '/cv',
    href: '/cv',
    title: 'CV',
    priority: '0.9',
    changefreq: 'monthly',
    description: 'Professional CV and experience',
    category: 'Professional',
    priorityLabel: 'High',
  },
  {
    url: '/speaking',
    href: '/speaking',
    title: 'Speaking & Events',
    priority: '0.8',
    changefreq: 'monthly',
    description: 'Speaking engagements and conference talks',
    category: 'Professional',
    priorityLabel: 'High',
  },
  {
    url: '/toolkit',
    href: '/toolkit',
    title: 'Toolkit',
    priority: '0.7',
    changefreq: 'monthly',
    description: 'Tools and gear I use for development',
    category: 'Resources',
    priorityLabel: 'Medium',
  },
  {
    url: '/photography',
    href: '/photography',
    title: 'Photography',
    priority: '0.7',
    changefreq: 'monthly',
    description: 'Photography portfolio and gallery',
    category: 'Creative',
    priorityLabel: 'Medium',
  },
  {
    url: '/contact',
    href: '/contact',
    title: 'Contact',
    priority: '0.6',
    changefreq: 'monthly',
    description: 'Contact information and ways to reach me',
    category: 'Communication',
    priorityLabel: 'Medium',
  },
  {
    url: '/chat',
    href: '/chat',
    title: 'Schedule Meeting',
    priority: '0.6',
    changefreq: 'monthly',
    description: 'Schedule a meeting or consultation',
    category: 'Communication',
    priorityLabel: 'Medium',
  },
  {
    url: '/sitemap',
    href: '/sitemap',
    title: 'Sitemap',
    priority: '0.3',
    changefreq: 'monthly',
    description: 'Site map and navigation guide',
    category: 'Navigation',
    priorityLabel: 'Low',
  },
];

export const externalLinks = [
  {
    href: '/blog',
    title: 'Blog',
    description: 'Technical articles and tutorials',
  },
  {
    href: 'https://pradumnasaraf.substack.com',
    title: 'Newsletter',
    description: 'Subscribe to my newsletter for updates',
  },
  {
    href: 'https://rebasemedia.com',
    title: 'Services',
    description: 'DevRel and consulting services',
  },
];
